version: '3.4'

services:
  presentationlayer:
    image: ${DOCKER_REGISTRY-}presentationlayer
    build:
      context: .
      dockerfile: PresentationLayer/Dockerfile
      
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build: 
      context: ClientApp
      dockerfile: Dockerfile