version: '3.4'

services:
  presentationlayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  frontend:
    environment:
      - NODE_ENV=Production
    ports:
      - "5000:80"

  postgres:
    environment:
      - POSTGRES_USER=Ruder
      - POSTGRES_PASSWORD=10152010i
      - POSTGRES_DB=postgres #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always